"""test_aibp_builder.py — AIBP email builder tests"""

from __future__ import annotations

import json
from unittest.mock import patch


def _make_body(content: str, bot_name: str = "TestBot", with_disclosure: bool = False) -> str:
    """Helper: build a valid L1 body with required elements"""
    parts = [content, f"\n\n-- {bot_name}"]
    if with_disclosure:
        parts.append(f"\n\n--\n{bot_name} | AI Agent\nThis message was generated by AI | Protocol: AIBP V1.0.0")
    parts.append("\nAlign Axiom 0: Human Sovereignty and Wellbeing. Version: AIBP V1.0.0. www.aibp.dev")
    return "".join(parts)


class TestBuildAibpMessage:
    def test_basic_build(self, mock_config):
        from aibp_builder import build_aibp_message
        body = _make_body("Hi there")
        result = build_aibp_message(
            config=mock_config, to="aibot-bob@gmail.com",
            aibp_type="CHAT", subject="Hello", body=body,
        )
        assert result["status"] == "ok"
        assert result["type"] == "CHAT"
        assert "[AIBP/CHAT] Hello" == result["subject"]
        assert result["message_id"]
        assert "raw_email" in result

    def test_subject_prefix(self, mock_config):
        from aibp_builder import build_aibp_message
        body = _make_body("Hello", with_disclosure=True)
        result = build_aibp_message(
            config=mock_config, to="bob@ex.com",
            aibp_type="INTRODUCE", subject="Hi", body=body,
        )
        assert result["subject"] == "[AIBP/INTRODUCE] Hi"

    def test_invalid_type_rejected(self, mock_config):
        from aibp_builder import build_aibp_message
        result = build_aibp_message(
            config=mock_config, to="bob@ex.com",
            aibp_type="HACKED", subject="Evil", body="...",
        )
        assert result["status"] == "error"
        assert result["error_code"] == "AIBP_TYPE_UNKNOWN"

    def test_type_case_insensitive(self, mock_config):
        from aibp_builder import build_aibp_message
        body = _make_body("Hello")
        result = build_aibp_message(
            config=mock_config, to="bob@ex.com",
            aibp_type="chat", subject="Hi", body=body,
        )
        assert result["status"] == "ok"
        assert result["type"] == "CHAT"

    def test_threading_headers(self, mock_config):
        from aibp_builder import build_aibp_message
        body = _make_body("Reply")
        result = build_aibp_message(
            config=mock_config, to="bob@ex.com",
            aibp_type="CHAT", subject="Re: Hello", body=body,
            in_reply_to="<orig@ex.com>",
            references="<prev@ex.com> <orig@ex.com>",
        )
        assert result["in_reply_to"] == "<orig@ex.com>"
        assert "<prev@ex.com>" in result["references"]

    def test_aibp_headers_in_raw(self, mock_config):
        from aibp_builder import build_aibp_message
        body = _make_body("Welcome!", with_disclosure=True)
        result = build_aibp_message(
            config=mock_config, to="bob@ex.com",
            aibp_type="WELCOME", subject="Hi", body=body,
        )
        raw = result["raw_email"]
        assert "X-AIBP-Version: AIBP V1.0.0" in raw
        assert "X-AIBP-Axiom-0: Human Sovereignty and Wellbeing" in raw
        assert "X-AIBP-Type: WELCOME" in raw
        assert "X-AIBP-Bot-Name: TestBot" in raw

    def test_pci_scope_for_commercial(self, mock_config):
        from aibp_builder import build_aibp_message
        body = _make_body("Offer details")
        result = build_aibp_message(
            config=mock_config, to="bob@ex.com",
            aibp_type="OFFER", subject="Deal", body=body,
        )
        assert "X-AIBP-PCI-Scope: excluded" in result["raw_email"]

    def test_no_pci_scope_for_chat(self, mock_config):
        from aibp_builder import build_aibp_message
        body = _make_body("Hello")
        result = build_aibp_message(
            config=mock_config, to="bob@ex.com",
            aibp_type="CHAT", subject="Hi", body=body,
        )
        assert "X-AIBP-PCI-Scope" not in result["raw_email"]

    def test_ai_footer_validation(self, mock_config):
        from aibp_builder import build_aibp_message
        from email import message_from_string
        body = _make_body("Hello", with_disclosure=True)
        result = build_aibp_message(
            config=mock_config, to="bob@ex.com",
            aibp_type="WELCOME", subject="Hi", body=body,
        )
        msg = message_from_string(result["raw_email"])
        decoded = msg.get_payload(decode=True).decode("utf-8")
        assert "Align Axiom 0: Human Sovereignty and Wellbeing" in decoded
        assert "TestBot" in decoded

    def test_thread_id_auto_lookup(self, mock_config, tmp_path):
        from aibp_builder import build_aibp_message
        body = _make_body("Reply")
        mock_thread_info = {
            "status": "ok",
            "in_reply_to": "<msg2@ex.com>",
            "references": "<msg1@ex.com> <msg2@ex.com>",
        }
        with patch("thread_manager.get_thread", return_value=mock_thread_info):
            result = build_aibp_message(
                config=mock_config, to="bob@ex.com",
                aibp_type="CHAT", subject="Re: Hi", body=body,
                thread_id="test-thread-123",
            )
            assert result["in_reply_to"] == "<msg2@ex.com>"
            assert "<msg1@ex.com>" in result["references"]

    def test_body_missing_seal_fails(self, mock_config):
        """ASSERT: body without closing seal is rejected"""
        from aibp_builder import build_aibp_message
        result = build_aibp_message(
            config=mock_config, to="bob@ex.com",
            aibp_type="CHAT", subject="Hi", body="Hello\n\n-- TestBot",
        )
        assert result["status"] == "error"
        assert result["error_code"] == "BODY_VALIDATION_FAILED"
        assert any("closing_seal" in a for a in result["assertions_failed"])

    def test_body_missing_signoff_fails(self, mock_config):
        """ASSERT: body without bot name is rejected"""
        from aibp_builder import build_aibp_message
        result = build_aibp_message(
            config=mock_config, to="bob@ex.com",
            aibp_type="CHAT", subject="Hi",
            body="Hello\nAlign Axiom 0: Human Sovereignty and Wellbeing. Version: AIBP V1.0.0. www.aibp.dev",
        )
        assert result["status"] == "error"
        assert any("sign_off" in a for a in result["assertions_failed"])

    def test_introduce_missing_disclosure_fails(self, mock_config):
        """ASSERT: INTRODUCE without AI disclosure is rejected"""
        from aibp_builder import build_aibp_message
        body = _make_body("Hello I am TestBot")  # no disclosure
        result = build_aibp_message(
            config=mock_config, to="bob@ex.com",
            aibp_type="INTRODUCE", subject="Hi", body=body,
        )
        assert result["status"] == "error"
        assert any("ai_disclosure" in a for a in result["assertions_failed"])
